#!/bin/sh

export PATH=${PATH}:/bin:/sbin:/usr/bin:/usr/sbin

mkdir /dev /run
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mdev -s
mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo "========Welcome========"
